### ISSUE TITLE
UpstreamServers - Input of list of upstream DNS servers

### ISSUE THREAD

**Issue by PR3R00T** [projectdiscovery/tinydns#72]
Looking at the current UpstreamServers option a list of DNS servers can be added as a string, Is it possible to add a File input of upstream providers. I think this will help massively with the rate limitting and distribution of the DNS lookups.

**Comment by dogancanbakir** [comment]
@PR3R00T, You can use the current `-upstream` to provide a file as input.

```console
$ cat list.txt 
1.1.1.1:53
8.8.8.8
$ go run . -upstream list.txt
[INF] Listening on: udp:127.0.0.1:53
```

I want to make sure I understand correctly. Is this what you were referring to? Please let me know.

**Comment by PR3R00T** [comment]
My apologies, yeah, this is what I was looking for! Thanks.
